drbdmon: remove unused variables to fix gcc16 errors
drbd-utils doesn't build with GCC 16:

[   38s] terminal/MDspTaskDetail.cpp: In member function virtual void MDspTaskDetail::display_content():
[   38s] terminal/MDspTaskDetail.cpp:263:22: error: variable skip_ctr set but not used [-Werror=unused-but-set-variable=]
[   38s]   263 |             uint32_t skip_ctr = 0;
[   38s]       |                      ^~~~~~~~
[   38s] terminal/MDspTaskDetail.cpp:277:22: error: variable print_ctr set but not used [-Werror=unused-but-set-variable=]
[   38s]   277 |             uint32_t print_ctr = 0;
[   38s]       |                      ^~~~~~~~~
[   38s] cc1plus: all warnings being treated as errors

Starting with GCC 16, var pre/postincrements and var @= expr no longer count as uses at some warning levels.

skip_ctr and print_ctr are set but not used so remove them to fix errors.

Signed-off-by: Su Yue <glass.su@suse.com>