Fix drbdsetup-8.4 build with -Werror=format-security
Building drbdsetup-8.4 with -Werror=format-security (enabled by default
for Debian builds) currently fails with the following errors:

  drbdsetup.c: In function ‘print_command_usage’:
  drbdsetup.c:2311:6: error: format not a string literal and no format arguments [-Werror=format-security]
        wrap_printf(4, "|resource" + first);
        ^
  drbdsetup.c:2315:6: error: format not a string literal and no format arguments [-Werror=format-security]
        wrap_printf(4, "|minor" + first);
        ^
  drbdsetup.c:2319:6: error: format not a string literal and no format arguments [-Werror=format-security]
        wrap_printf(4, "|all" + first);
        ^
  cc1: some warnings being treated as errors
  <builtin>: recipe for target 'drbdsetup.o' failed

Note that the way wrap_printf is called in this case is indeed safe, however we
comply with gcc by adding a "%s" format string to these calls.

Signed-off-by: Apollon Oikonomopoulos <apoikos@debian.org>